export type Locale =
  | "en" | "ur" | "hi" | "bn" | "pa" | "de" | "fr" | "es" | "it"
  | "pt" | "ru" | "uk" | "tr" | "zh" | "ja" | "ko" | "ar" | "fa"
  | "he" | "vi" | "id" | "ms" | "th" | "nl" | "pl" | "sv" | "da"
  | "no" | "fi" | "cs" | "ro";

export const LOCALE_KEY = "kurokuro-language";

type Dictionary = Record<string, string>;

const en: Dictionary = {
  web:"Web", images:"Images", videos:"Videos", news:"News", maps:"Maps", files:"Files", science:"Science",
  search:"Search", searchWeb:"Search the web", searchSuggestions:"Search suggestions", navigate:"navigate", close:"close",
  searchCategories:"Search categories", history:"History", bookmarks:"Bookmarks", settings:"Settings",
  tagline:"Search the web.", privacyNote:"Private by design. Your local history stays on your device.",
  back:"Kurokuro", searchHistory:"Search history", localPreferences:"Local preferences. No account required.",
  savedLocally:"Saved locally", searchSection:"Search", privacy:"Privacy", appearance:"Appearance", aboutPrivacy:"About privacy",
  safesearch:"SafeSearch", moderate:"Moderate", strict:"Strict", off:"Off", searchLanguage:"Search language",
  searchLanguageHelp:"Filters the search toward the selected language and also translates the Kurokuro interface when available.",
  region:"Region", global:"Global", defaultCategory:"Default category", defaultCategoryHelp:"Category used for new searches.",
  historyLabel:"Search history", historyHelp:"Keep searches only in this browser.", automaticDeletion:"Automatic history deletion",
  never:"Never", after7:"After 7 days", after30:"After 30 days", after90:"After 90 days",
  clearLocalData:"Clear local data", clear:"Clear", theme:"Theme", system:"System", light:"Light", dark:"Dark",
  themeHelp:"Use the system preference or force light/dark mode.", privacyHeadline:"Kurokuro controls your instance, not the entire internet.",
  privacyBody:"History and bookmarks stay local unless synchronization is deliberately added. Search requests still travel through SearXNG to the external providers your instance uses, so those providers may see information required to answer a request.",
  filters:"Filters", anyTime:"Any time", pastDay:"Past day", pastWeek:"Past week", pastMonth:"Past month", pastYear:"Past year",
  aggregated:"Aggregated search", resultsFor:"Results for", found:"found", save:"Save", saved:"Saved", copyLink:"Copy link", copied:"Copied", open:"Open",
  via:"via", by:"by", preview:"Preview", openOriginal:"Open original", imagePreview:"Image preview", closePreview:"Close preview",
  previousImage:"Previous image", nextImage:"Next image", previewUnavailable:"Preview unavailable", play:"Play", openVideo:"Open video",
tryBroader:"Try a broader search or switch to the Web tab.",
  noImages:"No previewable images found.", loading:"Searching", previous:"Previous", next:"Next",
  searchHistoryLives:"Your search history lives in this browser. It is never required for searching.",
  rememberSearches:"Remember searches locally so they can be found and re-run later.",
filterHistory:"Filter history", clearAll:"Clear all",
  historyDisabled:"History is disabled. New searches will not be stored.", noHistoryMatch:"No history matches that filter.",
  noSavedSearches:"No saved searches yet.", delete:"Delete", searchBookmarks:"Search bookmarks", allFolders:"All folders", newFolder:"New folder",
  bookmarksSubtitle:"A searchable local library for pages you want to keep.", noBookmarksMatch:"No bookmarks match your search.",
  nothingSaved:"Nothing saved yet. Use Save on a search result.", edit:"Edit", saveChanges:"Save changes", cancel:"Cancel",
  title:"Title", tags:"Tags, comma separated", notes:"Notes", noFolder:"No folder", folderName:"Folder name",
  foundVia:"found via", southAsia:"South Asia", europe:"Europe", eastAsia:"East Asia", middleEast:"Middle East", other:"Other",
  languageAll:"All languages", englishUS:"English — US", englishUK:"English — UK", chineseSimplified:"Chinese — Simplified", chineseTraditional:"Chinese — Traditional",
  resultsStatus:"Aggregated search", utilities:"Utilities", safeSearchHelp:"Protection level sent to the search backend.", regionHelp:"Preference passed to the search layer; provider support varies.", clearLocalDataHelp:"Delete history, bookmarks and bookmark folders from this browser.", olderRemoved:"Older entries are removed when this page is opened.", powerSearch:"Power search", powerSearchHelp:"Use advanced search operators directly in the search box. Kurokuro passes them through unchanged.", related:"Related", noResults:"No results found.", searchResultsPages:"Search results pages", page:"Page", searchFailed:"Search failed.", noSearchQuery:"No search query."
};

const dictionaries: Record<string, Dictionary> = {
  en,
  ur:{web:"ویب",images:"تصاویر",videos:"ویڈیوز",news:"خبریں",maps:"نقشے",files:"فائلیں",science:"سائنس",search:"تلاش",searchWeb:"ویب تلاش کریں",searchSuggestions:"تلاش کی تجاویز",navigate:"منتقل کریں",close:"بند کریں",searchCategories:"تلاش کی اقسام",history:"تاریخ",bookmarks:"بک مارکس",settings:"ترتیبات",tagline:"ویب تلاش کریں۔",privacyNote:"رازداری کے لیے بنایا گیا۔ آپ کی مقامی تاریخ آپ کے آلے پر رہتی ہے۔",back:"کوروکورو",searchHistory:"تلاش کی تاریخ",localPreferences:"مقامی ترجیحات۔ اکاؤنٹ کی ضرورت نہیں۔",savedLocally:"مقامی طور پر محفوظ",searchSection:"تلاش",privacy:"رازداری",appearance:"ظاہری شکل",aboutPrivacy:"رازداری کے بارے میں",safesearch:"محفوظ تلاش",moderate:"درمیانہ",strict:"سخت",off:"بند",searchLanguage:"تلاش کی زبان",searchLanguageHelp:"منتخب زبان کے مطابق تلاش کرتا ہے اور دستیاب ہونے پر کوروکورو کا انٹرفیس بھی بدل دیتا ہے۔",region:"علاقہ",global:"عالمی",defaultCategory:"ڈیفالٹ قسم",defaultCategoryHelp:"نئی تلاشوں کے لیے استعمال ہونے والی قسم۔",historyLabel:"تلاش کی تاریخ",historyHelp:"تلاشیں صرف اسی براؤزر میں رکھیں۔",automaticDeletion:"خودکار حذف",never:"کبھی نہیں",after7:"7 دن بعد",after30:"30 دن بعد",after90:"90 دن بعد",clearLocalData:"مقامی ڈیٹا صاف کریں",clear:"صاف کریں",theme:"تھیم",system:"سسٹم",light:"روشن",dark:"تاریک",themeHelp:"سسٹم ترجیح استعمال کریں یا روشن/تاریک موڈ منتخب کریں۔",filters:"فلٹرز",anyTime:"کسی بھی وقت",pastDay:"گزشتہ دن",pastWeek:"گزشتہ ہفتہ",pastMonth:"گزشتہ ماہ",pastYear:"گزشتہ سال",aggregated:"مجموعی تلاش",resultsFor:"نتائج برائے",found:"ملے",save:"محفوظ کریں",saved:"محفوظ",copyLink:"لنک کاپی کریں",copied:"کاپی ہوگیا",open:"کھولیں",preview:"پیش منظر",openOriginal:"اصل کھولیں",imagePreview:"تصویر کا پیش منظر",closePreview:"پیش منظر بند کریں",previousImage:"پچھلی تصویر",nextImage:"اگلی تصویر",previewUnavailable:"پیش منظر دستیاب نہیں",play:"چلائیں",openVideo:"ویڈیو کھولیں",noResults:"کوئی نتائج نہیں ملے۔",tryBroader:"وسیع تر تلاش آزمائیں یا ویب ٹیب منتخب کریں۔",noImages:"پیش منظر کے قابل تصاویر نہیں ملیں۔",loading:"تلاش جاری ہے",previous:"پچھلا",next:"اگلا",searchHistoryLives:"آپ کی تلاش کی تاریخ اسی براؤزر میں رہتی ہے۔ تلاش کے لیے اس کی ضرورت نہیں۔",rememberSearches:"تلاشیں مقامی طور پر محفوظ کریں تاکہ بعد میں انہیں تلاش اور دوبارہ چلا سکیں۔",olderRemoved:"پرانے اندراجات یہ صفحہ کھولنے پر حذف ہو جاتے ہیں۔",filterHistory:"تاریخ فلٹر کریں",clearAll:"سب صاف کریں",historyDisabled:"تلاش کی تاریخ بند ہے۔ نئی تلاشیں محفوظ نہیں ہوں گی۔",noHistoryMatch:"اس فلٹر سے کوئی تاریخ نہیں ملی۔",noSavedSearches:"ابھی کوئی محفوظ تلاش نہیں۔",delete:"حذف",searchBookmarks:"بک مارکس تلاش کریں",allFolders:"تمام فولڈرز",newFolder:"نیا فولڈر",bookmarksSubtitle:"ان صفحات کے لیے قابلِ تلاش مقامی لائبریری جنہیں آپ محفوظ رکھنا چاہتے ہیں۔",noBookmarksMatch:"آپ کی تلاش سے کوئی بک مارک نہیں ملا۔",nothingSaved:"ابھی کچھ محفوظ نہیں۔ تلاش کے نتیجے پر Save استعمال کریں۔",edit:"ترمیم",saveChanges:"تبدیلیاں محفوظ کریں",cancel:"منسوخ",title:"عنوان",tags:"ٹیگز، کوما سے الگ",notes:"نوٹس",noFolder:"کوئی فولڈر نہیں",folderName:"فولڈر کا نام"},
  hi:{web:"वेब",images:"चित्र",videos:"वीडियो",news:"समाचार",maps:"मानचित्र",files:"फ़ाइलें",science:"विज्ञान",search:"खोजें",searchWeb:"वेब खोजें",history:"इतिहास",bookmarks:"बुकमार्क",settings:"सेटिंग्स",tagline:"वेब खोजें।",privacyNote:"गोपनीयता के लिए बनाया गया। आपका स्थानीय इतिहास आपके डिवाइस पर रहता है।",searchHistory:"खोज इतिहास",localPreferences:"स्थानीय प्राथमिकताएँ। खाते की आवश्यकता नहीं।",savedLocally:"स्थानीय रूप से सहेजा गया",searchSection:"खोज",privacy:"गोपनीयता",appearance:"दिखावट",aboutPrivacy:"गोपनीयता के बारे में",safesearch:"सुरक्षित खोज",moderate:"मध्यम",strict:"सख्त",off:"बंद",searchLanguage:"खोज भाषा",searchLanguageHelp:"चयनित भाषा के अनुसार खोज करता है और उपलब्ध होने पर कूरोकुरो इंटरफ़ेस भी बदलता है।",region:"क्षेत्र",global:"वैश्विक",defaultCategory:"डिफ़ॉल्ट श्रेणी",historyLabel:"खोज इतिहास",automaticDeletion:"स्वचालित हटाना",never:"कभी नहीं",after7:"7 दिनों बाद",after30:"30 दिनों बाद",after90:"90 दिनों बाद",clearLocalData:"स्थानीय डेटा साफ़ करें",clear:"साफ़ करें",theme:"थीम",system:"सिस्टम",light:"हल्का",dark:"गहरा",filters:"फ़िल्टर",anyTime:"कभी भी",pastDay:"पिछला दिन",pastWeek:"पिछला सप्ताह",pastMonth:"पिछला महीना",pastYear:"पिछला वर्ष",aggregated:"एकत्रित खोज",resultsFor:"इसके परिणाम",found:"मिले",save:"सहेजें",saved:"सहेजा गया",copyLink:"लिंक कॉपी करें",copied:"कॉपी किया गया",open:"खोलें",preview:"पूर्वावलोकन",openOriginal:"मूल खोलें",imagePreview:"चित्र पूर्वावलोकन",closePreview:"पूर्वावलोकन बंद करें",previousImage:"पिछला चित्र",nextImage:"अगला चित्र",previewUnavailable:"पूर्वावलोकन उपलब्ध नहीं",play:"चलाएँ",openVideo:"वीडियो खोलें",noResults:"कोई परिणाम नहीं मिला।",tryBroader:"व्यापक खोज आज़माएँ या वेब टैब चुनें।",noImages:"पूर्वावलोकन योग्य चित्र नहीं मिले।",loading:"खोज जारी है",previous:"पिछला",next:"अगला",filterHistory:"इतिहास फ़िल्टर करें",clearAll:"सब साफ़ करें",historyDisabled:"इतिहास बंद है। नई खोजें सहेजी नहीं जाएँगी।",noHistoryMatch:"इस फ़िल्टर से कोई इतिहास नहीं मिला।",noSavedSearches:"अभी कोई सहेजी गई खोज नहीं।",delete:"हटाएँ",searchBookmarks:"बुकमार्क खोजें",allFolders:"सभी फ़ोल्डर",newFolder:"नया फ़ोल्डर",bookmarksSubtitle:"रखे जाने वाले पृष्ठों के लिए खोज योग्य स्थानीय लाइब्रेरी।",noBookmarksMatch:"आपकी खोज से कोई बुकमार्क नहीं मिला।",nothingSaved:"अभी कुछ सहेजा नहीं गया। खोज परिणाम पर Save इस्तेमाल करें।",edit:"संपादित करें",saveChanges:"परिवर्तन सहेजें",cancel:"रद्द करें",title:"शीर्षक",tags:"टैग, कॉमा से अलग",notes:"नोट्स",noFolder:"कोई फ़ोल्डर नहीं",folderName:"फ़ोल्डर का नाम"},
  es:{web:"Web",images:"Imágenes",videos:"Vídeos",news:"Noticias",maps:"Mapas",files:"Archivos",science:"Ciencia",search:"Buscar",searchWeb:"Buscar en la web",history:"Historial",bookmarks:"Marcadores",settings:"Ajustes",tagline:"Busca en la web.",privacyNote:"Privado por diseño. Tu historial local permanece en tu dispositivo.",searchHistory:"Historial de búsqueda",localPreferences:"Preferencias locales. No necesitas una cuenta.",savedLocally:"Guardado localmente",searchSection:"Búsqueda",privacy:"Privacidad",appearance:"Apariencia",aboutPrivacy:"Privacidad",safesearch:"Búsqueda segura",moderate:"Moderada",strict:"Estrica",off:"Desactivada",searchLanguage:"Idioma de búsqueda",searchLanguageHelp:"Filtra la búsqueda por el idioma seleccionado y traduce la interfaz de Kurokuro cuando está disponible.",region:"Región",global:"Global",defaultCategory:"Categoría predeterminada",historyLabel:"Historial de búsqueda",automaticDeletion:"Eliminación automática",never:"Nunca",after7:"Después de 7 días",after30:"Después de 30 días",after90:"Después de 90 días",clearLocalData:"Borrar datos locales",clear:"Borrar",theme:"Tema",system:"Sistema",light:"Claro",dark:"Oscuro",filters:"Filtros",anyTime:"Cualquier momento",pastDay:"Último día",pastWeek:"Última semana",pastMonth:"Último mes",pastYear:"Último año",aggregated:"Búsqueda agregada",resultsFor:"Resultados para",found:"encontrados",save:"Guardar",saved:"Guardado",copyLink:"Copiar enlace",copied:"Copiado",open:"Abrir",preview:"Vista previa",openOriginal:"Abrir original",imagePreview:"Vista previa de imagen",closePreview:"Cerrar vista previa",previousImage:"Imagen anterior",nextImage:"Imagen siguiente",previewUnavailable:"Vista previa no disponible",play:"Reproducir",openVideo:"Abrir vídeo",noResults:"No se encontraron resultados.",tryBroader:"Prueba una búsqueda más amplia o cambia a la pestaña Web.",noImages:"No se encontraron imágenes con vista previa.",loading:"Buscando",previous:"Anterior",next:"Siguiente",filterHistory:"Filtrar historial",clearAll:"Borrar todo",historyDisabled:"El historial está desactivado. Las nuevas búsquedas no se guardarán.",noHistoryMatch:"Ningún historial coincide con ese filtro.",noSavedSearches:"Aún no hay búsquedas guardadas.",delete:"Eliminar",searchBookmarks:"Buscar marcadores",allFolders:"Todas las carpetas",newFolder:"Nueva carpeta",bookmarksSubtitle:"Una biblioteca local y buscable para las páginas que quieres conservar.",noBookmarksMatch:"Ningún marcador coincide con tu búsqueda.",nothingSaved:"Aún no hay nada guardado. Usa Guardar en un resultado.",edit:"Editar",saveChanges:"Guardar cambios",cancel:"Cancelar",title:"Título",tags:"Etiquetas, separadas por comas",notes:"Notas",noFolder:"Sin carpeta",folderName:"Nombre de carpeta"},
  fr:{web:"Web",images:"Images",videos:"Vidéos",news:"Actualités",maps:"Cartes",files:"Fichiers",science:"Sciences",search:"Rechercher",searchWeb:"Rechercher sur le web",history:"Historique",bookmarks:"Favoris",settings:"Paramètres",tagline:"Recherchez sur le web.",privacyNote:"Privé par conception. Votre historique local reste sur votre appareil.",searchHistory:"Historique des recherches",localPreferences:"Préférences locales. Aucun compte requis.",savedLocally:"Enregistré localement",searchSection:"Recherche",privacy:"Confidentialité",appearance:"Apparence",aboutPrivacy:"Confidentialité",safesearch:"Recherche sécurisée",moderate:"Modérée",strict:"Stricte",off:"Désactivée",searchLanguage:"Langue de recherche",searchLanguageHelp:"Oriente la recherche vers la langue choisie et traduit aussi l’interface Kurokuro lorsqu’elle est disponible.",region:"Région",global:"Mondial",defaultCategory:"Catégorie par défaut",historyLabel:"Historique des recherches",automaticDeletion:"Suppression automatique",never:"Jamais",after7:"Après 7 jours",after30:"Après 30 jours",after90:"Après 90 jours",clearLocalData:"Effacer les données locales",clear:"Effacer",theme:"Thème",system:"Système",light:"Clair",dark:"Sombre",filters:"Filtres",anyTime:"À tout moment",pastDay:"Dernier jour",pastWeek:"Dernière semaine",pastMonth:"Dernier mois",pastYear:"Dernière année",aggregated:"Recherche agrégée",resultsFor:"Résultats pour",found:"trouvés",save:"Enregistrer",saved:"Enregistré",copyLink:"Copier le lien",copied:"Copié",open:"Ouvrir",preview:"Aperçu",openOriginal:"Ouvrir l’original",imagePreview:"Aperçu de l’image",closePreview:"Fermer l’aperçu",previousImage:"Image précédente",nextImage:"Image suivante",previewUnavailable:"Aperçu indisponible",play:"Lire",openVideo:"Ouvrir la vidéo",noResults:"Aucun résultat trouvé.",tryBroader:"Essayez une recherche plus large ou passez à l’onglet Web.",noImages:"Aucune image prévisualisable trouvée.",loading:"Recherche",previous:"Précédent",next:"Suivant",filterHistory:"Filtrer l’historique",clearAll:"Tout effacer",historyDisabled:"L’historique est désactivé. Les nouvelles recherches ne seront pas enregistrées.",noHistoryMatch:"Aucun historique ne correspond à ce filtre.",noSavedSearches:"Aucune recherche enregistrée.",delete:"Supprimer",searchBookmarks:"Rechercher dans les favoris",allFolders:"Tous les dossiers",newFolder:"Nouveau dossier",bookmarksSubtitle:"Une bibliothèque locale consultable pour les pages à conserver.",noBookmarksMatch:"Aucun favori ne correspond à votre recherche.",nothingSaved:"Rien n’est encore enregistré. Utilisez Enregistrer sur un résultat.",edit:"Modifier",saveChanges:"Enregistrer les modifications",cancel:"Annuler",title:"Titre",tags:"Étiquettes, séparées par des virgules",notes:"Notes",noFolder:"Aucun dossier",folderName:"Nom du dossier"},
  de:{web:"Web",images:"Bilder",videos:"Videos",news:"Nachrichten",maps:"Karten",files:"Dateien",science:"Wissenschaft",search:"Suchen",searchWeb:"Web durchsuchen",history:"Verlauf",bookmarks:"Lesezeichen",settings:"Einstellungen",tagline:"Das Web durchsuchen.",privacyNote:"Privat entwickelt. Dein lokaler Verlauf bleibt auf deinem Gerät.",searchHistory:"Suchverlauf",localPreferences:"Lokale Einstellungen. Kein Konto erforderlich.",savedLocally:"Lokal gespeichert",searchSection:"Suche",privacy:"Datenschutz",appearance:"Darstellung",aboutPrivacy:"Über Datenschutz",safesearch:"SafeSearch",moderate:"Moderat",strict:"Streng",off:"Aus",searchLanguage:"Suchsprache",searchLanguageHelp:"Richtet die Suche auf die ausgewählte Sprache aus und übersetzt die Kurokuro-Oberfläche, wenn verfügbar.",region:"Region",global:"Global",defaultCategory:"Standardkategorie",historyLabel:"Suchverlauf",automaticDeletion:"Automatische Löschung",never:"Nie",after7:"Nach 7 Tagen",after30:"Nach 30 Tagen",after90:"Nach 90 Tagen",clearLocalData:"Lokale Daten löschen",clear:"Löschen",theme:"Theme",system:"System",light:"Hell",dark:"Dunkel",filters:"Filter",anyTime:"Jederzeit",pastDay:"Letzter Tag",pastWeek:"Letzte Woche",pastMonth:"Letzter Monat",pastYear:"Letztes Jahr",aggregated:"Aggregierte Suche",resultsFor:"Ergebnisse für",found:"gefunden",save:"Speichern",saved:"Gespeichert",copyLink:"Link kopieren",copied:"Kopiert",open:"Öffnen",preview:"Vorschau",openOriginal:"Original öffnen",imagePreview:"Bildvorschau",closePreview:"Vorschau schließen",previousImage:"Vorheriges Bild",nextImage:"Nächstes Bild",previewUnavailable:"Vorschau nicht verfügbar",play:"Abspielen",openVideo:"Video öffnen",noResults:"Keine Ergebnisse gefunden.",tryBroader:"Versuche eine breitere Suche oder wechsle zum Web-Tab.",noImages:"Keine Vorschau-Bilder gefunden.",loading:"Suche",previous:"Zurück",next:"Weiter",filterHistory:"Verlauf filtern",clearAll:"Alles löschen",historyDisabled:"Der Verlauf ist deaktiviert. Neue Suchen werden nicht gespeichert.",noHistoryMatch:"Keine Verlaufseinträge passen zu diesem Filter.",noSavedSearches:"Noch keine gespeicherten Suchen.",delete:"Löschen",searchBookmarks:"Lesezeichen durchsuchen",allFolders:"Alle Ordner",newFolder:"Neuer Ordner",bookmarksSubtitle:"Eine durchsuchbare lokale Bibliothek für Seiten, die du behalten möchtest.",noBookmarksMatch:"Keine Lesezeichen passen zu deiner Suche.",nothingSaved:"Noch nichts gespeichert. Nutze Speichern bei einem Suchergebnis.",edit:"Bearbeiten",saveChanges:"Änderungen speichern",cancel:"Abbrechen",title:"Titel",tags:"Tags, durch Kommas getrennt",notes:"Notizen",noFolder:"Kein Ordner",folderName:"Ordnername"}
};

const extra: Record<string, Partial<Dictionary>> = {
  pa:{web:"ਵੈੱਬ",images:"ਤਸਵੀਰਾਂ",videos:"ਵੀਡੀਓ",news:"ਖ਼ਬਰਾਂ",maps:"ਨਕਸ਼ੇ",files:"ਫ਼ਾਈਲਾਂ",science:"ਵਿਗਿਆਨ",search:"ਖੋਜ",searchWeb:"ਵੈੱਬ ਖੋਜੋ",history:"ਇਤਿਹਾਸ",bookmarks:"ਬੁੱਕਮਾਰਕ",settings:"ਸੈਟਿੰਗਾਂ",tagline:"ਵੈੱਬ ਖੋਜੋ।",privacyNote:"ਨਿੱਜਤਾ ਲਈ ਬਣਾਇਆ ਗਿਆ। ਤੁਹਾਡਾ ਸਥਾਨਕ ਇਤਿਹਾਸ ਤੁਹਾਡੀ ਡਿਵਾਈਸ 'ਤੇ ਰਹਿੰਦਾ ਹੈ।",filters:"ਫਿਲਟਰ",anyTime:"ਕਿਸੇ ਵੀ ਸਮੇਂ",pastDay:"ਪਿਛਲਾ ਦਿਨ",pastWeek:"ਪਿਛਲਾ ਹਫ਼ਤਾ",pastMonth:"ਪਿਛਲਾ ਮਹੀਨਾ",pastYear:"ਪਿਛਲਾ ਸਾਲ",save:"ਸੰਭਾਲੋ",saved:"ਸੰਭਾਲਿਆ",open:"ਖੋਲ੍ਹੋ",preview:"ਝਲਕ",delete:"ਮਿਟਾਓ"},
  bn:{web:"ওয়েব",images:"ছবি",videos:"ভিডিও",news:"সংবাদ",maps:"মানচিত্র",files:"ফাইল",science:"বিজ্ঞান",search:"অনুসন্ধান",searchWeb:"ওয়েবে অনুসন্ধান করুন",history:"ইতিহাস",bookmarks:"বুকমার্ক",settings:"সেটিংস",tagline:"ওয়েবে অনুসন্ধান করুন।",privacyNote:"গোপনীয়তার জন্য তৈরি। আপনার স্থানীয় ইতিহাস আপনার ডিভাইসেই থাকে।",filters:"ফিল্টার",anyTime:"যেকোনো সময়",pastDay:"গত দিন",pastWeek:"গত সপ্তাহ",pastMonth:"গত মাস",pastYear:"গত বছর",save:"সংরক্ষণ",saved:"সংরক্ষিত",open:"খুলুন",preview:"প্রিভিউ",delete:"মুছুন"},
  ru:{web:"Веб",images:"Изображения",videos:"Видео",news:"Новости",maps:"Карты",files:"Файлы",science:"Наука",search:"Поиск",searchWeb:"Поиск в интернете",history:"История",bookmarks:"Закладки",settings:"Настройки",tagline:"Ищите в интернете.",privacyNote:"Приватность по умолчанию. Локальная история остаётся на устройстве.",filters:"Фильтры",anyTime:"Любое время",pastDay:"Последний день",pastWeek:"Последняя неделя",pastMonth:"Последний месяц",pastYear:"Последний год",save:"Сохранить",saved:"Сохранено",open:"Открыть",preview:"Предпросмотр",delete:"Удалить"},
  uk:{web:"Веб",images:"Зображення",videos:"Відео",news:"Новини",maps:"Карти",files:"Файли",science:"Наука",search:"Пошук",searchWeb:"Шукати в інтернеті",history:"Історія",bookmarks:"Закладки",settings:"Налаштування",tagline:"Шукайте в інтернеті.",privacyNote:"Приватність за задумом. Локальна історія залишається на пристрої.",filters:"Фільтри",anyTime:"Будь-коли",pastDay:"Останній день",pastWeek:"Останній тиждень",pastMonth:"Останній місяць",pastYear:"Останній рік",save:"Зберегти",saved:"Збережено",open:"Відкрити",preview:"Попередній перегляд",delete:"Видалити"},
  tr:{web:"Web",images:"Görseller",videos:"Videolar",news:"Haberler",maps:"Haritalar",files:"Dosyalar",science:"Bilim",search:"Ara",searchWeb:"Web'de ara",history:"Geçmiş",bookmarks:"Yer imleri",settings:"Ayarlar",tagline:"Web'de arayın.",privacyNote:"Gizlilik odaklı. Yerel geçmişiniz cihazınızda kalır.",filters:"Filtreler",anyTime:"Her zaman",pastDay:"Son gün",pastWeek:"Son hafta",pastMonth:"Son ay",pastYear:"Son yıl",save:"Kaydet",saved:"Kaydedildi",open:"Aç",preview:"Önizleme",delete:"Sil"},
  it:{web:"Web",images:"Immagini",videos:"Video",news:"Notizie",maps:"Mappe",files:"File",science:"Scienza",search:"Cerca",searchWeb:"Cerca sul web",history:"Cronologia",bookmarks:"Segnalibri",settings:"Impostazioni",tagline:"Cerca sul web.",privacyNote:"Privato per design. La cronologia locale resta sul dispositivo.",filters:"Filtri",anyTime:"Qualsiasi momento",pastDay:"Ultimo giorno",pastWeek:"Ultima settimana",pastMonth:"Ultimo mese",pastYear:"Ultimo anno",save:"Salva",saved:"Salvato",open:"Apri",preview:"Anteprima",delete:"Elimina"},
  pt:{web:"Web",images:"Imagens",videos:"Vídeos",news:"Notícias",maps:"Mapas",files:"Ficheiros",science:"Ciência",search:"Pesquisar",searchWeb:"Pesquisar na web",history:"Histórico",bookmarks:"Marcadores",settings:"Definições",tagline:"Pesquise na web.",privacyNote:"Privado por design. O histórico local fica no seu dispositivo.",filters:"Filtros",anyTime:"Qualquer altura",pastDay:"Último dia",pastWeek:"Última semana",pastMonth:"Último mês",pastYear:"Último ano",save:"Guardar",saved:"Guardado",open:"Abrir",preview:"Pré-visualização",delete:"Eliminar"},
  nl:{web:"Web",images:"Afbeeldingen",videos:"Video's",news:"Nieuws",maps:"Kaarten",files:"Bestanden",science:"Wetenschap",search:"Zoeken",searchWeb:"Zoek op het web",history:"Geschiedenis",bookmarks:"Bladwijzers",settings:"Instellingen",tagline:"Zoek op het web.",privacyNote:"Privé ontworpen. Je lokale geschiedenis blijft op je apparaat.",filters:"Filters",anyTime:"Altijd",pastDay:"Afgelopen dag",pastWeek:"Afgelopen week",pastMonth:"Afgelopen maand",pastYear:"Afgelopen jaar",save:"Opslaan",saved:"Opgeslagen",open:"Openen",preview:"Voorbeeld",delete:"Verwijderen"},
  zh:{web:"网页",images:"图片",videos:"视频",news:"新闻",maps:"地图",files:"文件",science:"科学",search:"搜索",searchWeb:"搜索网页",history:"历史记录",bookmarks:"书签",settings:"设置",tagline:"搜索网页。",privacyNote:"以隐私为设计核心。本地历史记录保存在你的设备上。",filters:"筛选",anyTime:"任何时间",pastDay:"过去一天",pastWeek:"过去一周",pastMonth:"过去一个月",pastYear:"过去一年",save:"保存",saved:"已保存",open:"打开",preview:"预览",delete:"删除"},
  ja:{web:"ウェブ",images:"画像",videos:"動画",news:"ニュース",maps:"地図",files:"ファイル",science:"科学",search:"検索",searchWeb:"ウェブを検索",history:"履歴",bookmarks:"ブックマーク",settings:"設定",tagline:"ウェブを検索。",privacyNote:"プライバシーを重視。ローカル履歴は端末に保存されます。",filters:"フィルター",anyTime:"期間指定なし",pastDay:"過去1日",pastWeek:"過去1週間",pastMonth:"過去1か月",pastYear:"過去1年",save:"保存",saved:"保存済み",open:"開く",preview:"プレビュー",delete:"削除"},
  ko:{web:"웹",images:"이미지",videos:"동영상",news:"뉴스",maps:"지도",files:"파일",science:"과학",search:"검색",searchWeb:"웹 검색",history:"기록",bookmarks:"북마크",settings:"설정",tagline:"웹을 검색하세요.",privacyNote:"개인정보 보호를 중심으로 설계되었습니다. 로컬 기록은 기기에 남습니다.",filters:"필터",anyTime:"언제든지",pastDay:"지난 하루",pastWeek:"지난주",pastMonth:"지난달",pastYear:"지난해",save:"저장",saved:"저장됨",open:"열기",preview:"미리보기",delete:"삭제"},
  ar:{web:"الويب",images:"الصور",videos:"الفيديو",news:"الأخبار",maps:"الخرائط",files:"الملفات",science:"العلوم",search:"بحث",searchWeb:"ابحث في الويب",history:"السجل",bookmarks:"الإشارات المرجعية",settings:"الإعدادات",tagline:"ابحث في الويب.",privacyNote:"الخصوصية أولاً. يبقى السجل المحلي على جهازك.",filters:"الفلاتر",anyTime:"أي وقت",pastDay:"اليوم الماضي",pastWeek:"الأسبوع الماضي",pastMonth:"الشهر الماضي",pastYear:"السنة الماضية",save:"حفظ",saved:"محفوظ",open:"فتح",preview:"معاينة",delete:"حذف"},
  fa:{web:"وب",images:"تصاویر",videos:"ویدیوها",news:"اخبار",maps:"نقشه‌ها",files:"فایل‌ها",science:"علم",search:"جستجو",searchWeb:"جستجوی وب",history:"تاریخچه",bookmarks:"نشانک‌ها",settings:"تنظیمات",tagline:"در وب جستجو کنید.",privacyNote:"حریم خصوصی در طراحی. تاریخچه محلی روی دستگاه شما می‌ماند.",filters:"فیلترها",anyTime:"هر زمان",pastDay:"روز گذشته",pastWeek:"هفته گذشته",pastMonth:"ماه گذشته",pastYear:"سال گذشته",save:"ذخیره",saved:"ذخیره شد",open:"باز کردن",preview:"پیش‌نمایش",delete:"حذف"},
  he:{web:"אינטרנט",images:"תמונות",videos:"סרטונים",news:"חדשות",maps:"מפות",files:"קבצים",science:"מדע",search:"חיפוש",searchWeb:"חיפוש באינטרנט",history:"היסטוריה",bookmarks:"סימניות",settings:"הגדרות",tagline:"חפשו באינטרנט.",privacyNote:"פרטיות כברירת מחדל. ההיסטוריה המקומית נשארת במכשיר.",filters:"מסננים",anyTime:"בכל זמן",pastDay:"היום האחרון",pastWeek:"השבוע האחרון",pastMonth:"החודש האחרון",pastYear:"השנה האחרונה",save:"שמור",saved:"נשמר",open:"פתח",preview:"תצוגה מקדימה",delete:"מחק"},
  vi:{web:"Web",images:"Hình ảnh",videos:"Video",news:"Tin tức",maps:"Bản đồ",files:"Tệp",science:"Khoa học",search:"Tìm kiếm",searchWeb:"Tìm kiếm trên web",history:"Lịch sử",bookmarks:"Dấu trang",settings:"Cài đặt",tagline:"Tìm kiếm trên web.",privacyNote:"Riêng tư theo thiết kế. Lịch sử cục bộ nằm trên thiết bị của bạn.",filters:"Bộ lọc",anyTime:"Mọi lúc",pastDay:"Ngày qua",pastWeek:"Tuần qua",pastMonth:"Tháng qua",pastYear:"Năm qua",save:"Lưu",saved:"Đã lưu",open:"Mở",preview:"Xem trước",delete:"Xóa"},
  id:{web:"Web",images:"Gambar",videos:"Video",news:"Berita",maps:"Peta",files:"File",science:"Sains",search:"Cari",searchWeb:"Cari di web",history:"Riwayat",bookmarks:"Bookmark",settings:"Pengaturan",tagline:"Cari di web.",privacyNote:"Privasi sejak awal. Riwayat lokal tetap di perangkat Anda.",filters:"Filter",anyTime:"Kapan saja",pastDay:"Hari terakhir",pastWeek:"Minggu terakhir",pastMonth:"Bulan terakhir",pastYear:"Tahun terakhir",save:"Simpan",saved:"Tersimpan",open:"Buka",preview:"Pratinjau",delete:"Hapus"},
  ms:{web:"Web",images:"Imej",videos:"Video",news:"Berita",maps:"Peta",files:"Fail",science:"Sains",search:"Cari",searchWeb:"Cari di web",history:"Sejarah",bookmarks:"Penanda buku",settings:"Tetapan",tagline:"Cari di web.",privacyNote:"Privasi mengikut reka bentuk. Sejarah tempatan kekal pada peranti anda.",filters:"Penapis",anyTime:"Bila-bila masa",pastDay:"Hari lalu",pastWeek:"Minggu lalu",pastMonth:"Bulan lalu",pastYear:"Tahun lalu",save:"Simpan",saved:"Disimpan",open:"Buka",preview:"Pratonton",delete:"Padam"},
  th:{web:"เว็บ",images:"รูปภาพ",videos:"วิดีโอ",news:"ข่าว",maps:"แผนที่",files:"ไฟล์",science:"วิทยาศาสตร์",search:"ค้นหา",searchWeb:"ค้นหาเว็บ",history:"ประวัติ",bookmarks:"บุ๊กมาร์ก",settings:"การตั้งค่า",tagline:"ค้นหาเว็บ",privacyNote:"ออกแบบโดยคำนึงถึงความเป็นส่วนตัว ประวัติในเครื่องจะอยู่บนอุปกรณ์ของคุณ",filters:"ตัวกรอง",anyTime:"เวลาใดก็ได้",pastDay:"วันที่ผ่านมา",pastWeek:"สัปดาห์ที่ผ่านมา",pastMonth:"เดือนที่ผ่านมา",pastYear:"ปีที่ผ่านมา",save:"บันทึก",saved:"บันทึกแล้ว",open:"เปิด",preview:"ดูตัวอย่าง",delete:"ลบ"},
  sv:{web:"Webb",images:"Bilder",videos:"Videor",news:"Nyheter",maps:"Kartor",files:"Filer",science:"Vetenskap",search:"Sök",searchWeb:"Sök på webben",history:"Historik",bookmarks:"Bokmärken",settings:"Inställningar",tagline:"Sök på webben.",privacyNote:"Privat från början. Din lokala historik stannar på enheten.",filters:"Filter",anyTime:"När som helst",pastDay:"Senaste dygnet",pastWeek:"Senaste veckan",pastMonth:"Senaste månaden",pastYear:"Senaste året",save:"Spara",saved:"Sparad",open:"Öppna",preview:"Förhandsvisning",delete:"Ta bort"},
  da:{web:"Web",images:"Billeder",videos:"Videoer",news:"Nyheder",maps:"Kort",files:"Filer",science:"Videnskab",search:"Søg",searchWeb:"Søg på nettet",history:"Historik",bookmarks:"Bogmærker",settings:"Indstillinger",tagline:"Søg på nettet.",privacyNote:"Privat som standard. Din lokale historik bliver på enheden.",filters:"Filtre",anyTime:"Når som helst",pastDay:"Sidste døgn",pastWeek:"Sidste uge",pastMonth:"Sidste måned",pastYear:"Sidste år",save:"Gem",saved:"Gemt",open:"Åbn",preview:"Forhåndsvisning",delete:"Slet"},
  no:{web:"Nett",images:"Bilder",videos:"Videoer",news:"Nyheter",maps:"Kart",files:"Filer",science:"Vitenskap",search:"Søk",searchWeb:"Søk på nettet",history:"Historikk",bookmarks:"Bokmerker",settings:"Innstillinger",tagline:"Søk på nettet.",privacyNote:"Privat som standard. Lokal historikk blir på enheten.",filters:"Filtre",anyTime:"Når som helst",pastDay:"Siste døgn",pastWeek:"Siste uke",pastMonth:"Siste måned",pastYear:"Siste år",save:"Lagre",saved:"Lagret",open:"Åpne",preview:"Forhåndsvisning",delete:"Slett"},
  fi:{web:"Web",images:"Kuvat",videos:"Videot",news:"Uutiset",maps:"Kartat",files:"Tiedostot",science:"Tiede",search:"Hae",searchWeb:"Hae verkosta",history:"Historia",bookmarks:"Kirjanmerkit",settings:"Asetukset",tagline:"Hae verkosta.",privacyNote:"Yksityisyys ensin. Paikallinen historia säilyy laitteellasi.",filters:"Suodattimet",anyTime:"Milloin tahansa",pastDay:"Viime päivä",pastWeek:"Viime viikko",pastMonth:"Viime kuukausi",pastYear:"Viime vuosi",save:"Tallenna",saved:"Tallennettu",open:"Avaa",preview:"Esikatselu",delete:"Poista"},
  cs:{web:"Web",images:"Obrázky",videos:"Videa",news:"Zprávy",maps:"Mapy",files:"Soubory",science:"Věda",search:"Hledat",searchWeb:"Hledat na webu",history:"Historie",bookmarks:"Záložky",settings:"Nastavení",tagline:"Hledejte na webu.",privacyNote:"Soukromí podle návrhu. Místní historie zůstává v zařízení.",filters:"Filtry",anyTime:"Kdykoli",pastDay:"Poslední den",pastWeek:"Poslední týden",pastMonth:"Poslední měsíc",pastYear:"Poslední rok",save:"Uložit",saved:"Uloženo",open:"Otevřít",preview:"Náhled",delete:"Smazat"},
  ro:{web:"Web",images:"Imagini",videos:"Videoclipuri",news:"Știri",maps:"Hărți",files:"Fișiere",science:"Știință",search:"Caută",searchWeb:"Caută pe web",history:"Istoric",bookmarks:"Marcaje",settings:"Setări",tagline:"Caută pe web.",privacyNote:"Privat prin design. Istoricul local rămâne pe dispozitiv.",filters:"Filtre",anyTime:"Oricând",pastDay:"Ultima zi",pastWeek:"Ultima săptămână",pastMonth:"Ultima lună",pastYear:"Ultimul an",save:"Salvează",saved:"Salvat",open:"Deschide",preview:"Previzualizare",delete:"Șterge"}
};

for (const [key, value] of Object.entries(extra)) dictionaries[key] = { ...en, ...Object.fromEntries(Object.entries(value).filter(([, translated]) => typeof translated === "string")) };
for (const [key, value] of Object.entries(dictionaries)) dictionaries[key] = { ...en, ...value };

export function normalizeLocale(value: string | null | undefined): Locale {
  const raw = (value || "en").toLowerCase();
  const base = raw.split("-")[0];
  return (dictionaries[base] ? base : "en") as Locale;
}

export function getDictionary(locale: string | null | undefined) {
  return dictionaries[normalizeLocale(locale)] || en;
}
