services:
  searxng:
    image: docker.io/searxng/searxng:2026.9.25-12f8b6515
    platform: linux/amd64
    container_name: kurokuro-searxng
    restart: unless-stopped

    ports:
      - "8080:8080"

    volumes:
      - ./core-config:/etc/searxng:rw
      - searxng-cache:/var/cache/searxng:rw

    depends_on:
      - valkey

    environment:
      SEARXNG_VALKEY_URL: valkey://valkey:6379/0

  valkey:
    image: docker.io/valkey/valkey:8-alpine
    platform: linux/amd64
    container_name: kurokuro-valkey
    restart: unless-stopped

    command:
      - valkey-server
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning

    volumes:
      - valkey-data:/data

volumes:
  searxng-cache:
  valkey-data: